language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_59ec26d870d2_key -iv $encrypted_59ec26d870d2_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
