language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_674952525038_key -iv $encrypted_674952525038_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
